---
- name: Class 5 Exercise 3
  hosts: arista
  tasks:
     - name: Ping'em
       ping:

     - name: Create VLANS 67,78,89
       arista_vlan: vlanid={{item.id}} name={{item.name}}
                 eapi_username={{ eapi_username }}
                 eapi_password={{ eapi_password }}
                 eapi_hostname={{ eapi_hostname }}
                 eapi_port={{ eapi_port }}
       with_items:
         - { id: 67 , name: CURRENT-NAME }
         - { id: 78 , name: TR-THIN-10.170.16.0/23 }
         - { id: 89 , name: dqq }

