# 2. Use Ansible to configure your 'primary Ethernet interface' as follows:
# 
# interface description:     *** IN USE ***
# switchport mode:          access
# VLAN:                     <one of the VLANs created in exercise1>
# 
# Your 'primary Ethernet interface' is specified in your ~/ansible-hosts file.
# 
# If your primary interface is already IN USE (by someone else), then use your
# secondary interface (once again specified in ~/ansible-hosts).  You can
# determine if an interface is already in use by SSH'ing into the switch.
# Reminder, do NOT use Ethernet1.
# 
---
- name: Class 4 Exercise 2
  hosts: arista
  tasks:
    - name: Assign description to Eth3
      eos_interface: name=Ethernet3 description="*** IN USE ***"
                 eapi_username={{ eapi_username }}
                 eapi_password={{ eapi_password }}
                 eapi_hostname={{ eapi_hostname }}
                 eapi_port={{ eapi_port }}
    - name: Assign vlan 89 to Eth3
      eos_switchport: name=Ethernet3 mode=access access_vlan=89 trunk_allowed_vlans=all
                 eapi_username={{ eapi_username }}
                 eapi_password={{ eapi_password }}
                 eapi_hostname={{ eapi_hostname }}
                 eapi_port={{ eapi_port }}
