# 3. Use Ansible to configure your 'primary Ethernet interface' as follows:
#
# switchport mode:           trunk
# trunk native VLAN:        VLAN1
# trunk allowed VLANs:    <the three VLANs created in exercise1>
---
- name: Class 4 Exercise 3
  hosts: arista
  tasks:
    - name: Assign vlan 67,78,89 to trunk Eth3
      eos_switchport: name=Ethernet3 mode=trunk access_vlan=1 trunk_allowed_vlans=67,78,89 trunk_native_vlan=1
                 eapi_username={{ eapi_username }}
                 eapi_password={{ eapi_password }}
                 eapi_hostname={{ eapi_hostname }}
                 eapi_port={{ eapi_port }}
