# 4. Use Ansible to restore your 'primary Ethernet interface' back to the
# following (or your secondary interface depending on which one you used):
#
# description:                    <none>
# switchport mode:           access
# access VLAN:                1
# trunk allowed VLANs:    all
#
# Also use Ansible to remove the three VLANs that you configured.
#
---
- name: Class 4 Exercise 4
  hosts: arista
  tasks:
    - name: Remove description from Eth3
      eos_interface: name=Ethernet3 null_as_default=true
                 eapi_username={{ eapi_username }}
                 eapi_password={{ eapi_password }}
                 eapi_hostname={{ eapi_hostname }}
                 eapi_port={{ eapi_port }}
    - name: Default to vlan 1 on Eth3
      eos_switchport: name=Ethernet3 mode=access access_vlan=1 trunk_allowed_vlans=all trunk_native_vlan=1
                 eapi_username={{ eapi_username }}
                 eapi_password={{ eapi_password }}
                 eapi_hostname={{ eapi_hostname }}
                 eapi_port={{ eapi_port }}
    - name: Remove vlans 67,78,89
      eos_vlan: name={{item}} null_as_default=true state=unconfigured
                 eapi_username={{ eapi_username }}
                 eapi_password={{ eapi_password }}
                 eapi_hostname={{ eapi_hostname }}
                 eapi_port={{ eapi_port }}
      with_items:
        - 67
        - 78
        - 89
